'use client'

import { Inter } from 'next/font/google'
import { CountryDataProvider } from './hooks/useCountryData'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <CountryDataProvider>
        <body className={inter.className}>{children}</body>
      </CountryDataProvider>
    </html>
  )
}
